nyc_data:
  folder_path: data\nyc_taxi
weather_data:
  folder_path: data\weather
datalake:
  endpoint: localhost:9000
  bucket_name_1: raw
  bucket_name_2: processed
  bucket_name_3: sandbox
  taxi_folder_name: nyc_taxi
  new_taxi_folder_name: new_nyc_taxi
  weather_folder_name: weather
  access_key: minio_access_key
  secret_key: minio_secret_key
